<template><div><h1 id="信息科技八年级-第五单元-第22课-健康生活新设备" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第五单元-第22课-健康生活新设备"><span>信息科技八年级-第五单元-第22课-健康生活新设备</span></a></h1>
<p>PYTHON代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> oled<span class="token punctuation">,</span> mqttclient<span class="token punctuation">,</span> wifi</span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span> timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span> client_id<span class="token operator">=</span><span class="token string">'a73ac32c25'</span><span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'a73acV5ktf'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'a73acNjTf7'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">receive_a73acOQbFR</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    <span class="token keyword">global</span> xb<span class="token punctuation">,</span> bj<span class="token punctuation">,</span> msg<span class="token punctuation">,</span> m<span class="token punctuation">,</span> f</span>
<span class="line">    msg <span class="token operator">=</span> <span class="token punctuation">(</span>mqttclient<span class="token punctuation">.</span>message<span class="token punctuation">(</span><span class="token string">"a73acOQbFR"</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">.</span>split<span class="token punctuation">(</span><span class="token string">','</span><span class="token punctuation">)</span></span>
<span class="line">    bj <span class="token operator">=</span> msg<span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line">    xb <span class="token operator">=</span> msg<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token keyword">if</span> xb <span class="token operator">==</span> <span class="token string">'男'</span><span class="token punctuation">:</span></span>
<span class="line">        f<span class="token punctuation">[</span>bj<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">(</span>f<span class="token punctuation">[</span>bj<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">else</span><span class="token punctuation">:</span></span>
<span class="line">        m<span class="token punctuation">[</span>bj<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">(</span>m<span class="token punctuation">[</span>bj<span class="token punctuation">]</span> <span class="token operator">+</span> <span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">    oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'班级    男生    女生\n1           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>f<span class="token punctuation">[</span><span class="token string">'1班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>m<span class="token punctuation">[</span><span class="token string">'1班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\n2           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>f<span class="token punctuation">[</span><span class="token string">'2班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>m<span class="token punctuation">[</span><span class="token string">'2班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\n3           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>f<span class="token punctuation">[</span><span class="token string">'3班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'           '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>m<span class="token punctuation">[</span><span class="token string">'3班'</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">f <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">"1班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">"2班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">"3班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">}</span></span>
<span class="line">m <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token string">"1班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">"2班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">,</span> <span class="token string">"3班"</span><span class="token punctuation">:</span><span class="token number">0</span><span class="token punctuation">}</span></span>
<span class="line">mqttclient<span class="token punctuation">.</span>received<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">"a73acOQbFR"</span><span class="token punctuation">,</span> callback<span class="token operator">=</span>receive_a73acOQbFR<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./py/u5l22_学习活动3-反馈.py" download>点击下载-u5l22_学习活动3-反馈.py</a></p>
</div></template>


