<template><div><h1 id="信息科技八年级-第五单元-第22课-健康生活新设备" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第五单元-第22课-健康生活新设备"><span>信息科技八年级-第五单元-第22课-健康生活新设备</span></a></h1>
<p>PYTHON代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> oled<span class="token punctuation">,</span> button<span class="token punctuation">,</span> ultrasonic<span class="token punctuation">,</span> mqttclient<span class="token punctuation">,</span> wifi</span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span> timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span> client_id<span class="token operator">=</span><span class="token string">'a73ac10630'</span><span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'a73acV7awT'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'a73acMdbXg'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> time</span>
<span class="line">k1 <span class="token operator">=</span> button<span class="token punctuation">(</span>button<span class="token punctuation">.</span>a<span class="token punctuation">)</span></span>
<span class="line">k2 <span class="token operator">=</span> button<span class="token punctuation">(</span>button<span class="token punctuation">.</span>b<span class="token punctuation">)</span></span>
<span class="line">sonic <span class="token operator">=</span> ultrasonic<span class="token punctuation">(</span>sda<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">,</span>scl<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">H <span class="token operator">=</span> <span class="token number">200</span></span>
<span class="line">height <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line">c <span class="token operator">=</span> <span class="token string">'1班'</span></span>
<span class="line"><span class="token keyword">while</span> <span class="token boolean">True</span><span class="token punctuation">:</span></span>
<span class="line">    height <span class="token operator">=</span> H <span class="token operator">-</span> sonic<span class="token punctuation">.</span>distance<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'身高：'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>height<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'cm\n男生请按 k1\n女生请按 k2'</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> k1<span class="token punctuation">.</span>status<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">:</span></span>
<span class="line">        mqttclient<span class="token punctuation">.</span>publish<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">'a73acOQbFR'</span><span class="token punctuation">,</span> content<span class="token operator">=</span><span class="token builtin">str</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">',男,'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>height<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> k2<span class="token punctuation">.</span>status<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">:</span></span>
<span class="line">        mqttclient<span class="token punctuation">.</span>publish<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">'a73acOQbFR'</span><span class="token punctuation">,</span> content<span class="token operator">=</span><span class="token builtin">str</span><span class="token punctuation">(</span>c<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">',女,'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>height<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    time<span class="token punctuation">.</span>sleep<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./py/u5l22_学习活动3-测量.py" download>点击下载-u5l22_学习活动3-测量.py</a></p>
</div></template>


