<template><div><h1 id="信息科技八年级-第五单元-第24课-农业生产新模式" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第五单元-第24课-农业生产新模式"><span>信息科技八年级-第五单元-第24课-农业生产新模式</span></a></h1>
<p>PYTHON代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> oled<span class="token punctuation">,</span> rfid<span class="token punctuation">,</span> button<span class="token punctuation">,</span> ultrasonic<span class="token punctuation">,</span> wifi<span class="token punctuation">,</span> mqttclient</span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span> timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span> client_id<span class="token operator">=</span><span class="token string">'5b47f14909'</span><span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'5b47fkYKD0'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'5b47f9KEFp'</span><span class="token punctuation">)</span></span>
<span class="line">scan_rfid <span class="token operator">=</span> rfid<span class="token punctuation">(</span>sda<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">,</span> scl<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">k <span class="token operator">=</span> button<span class="token punctuation">(</span>button<span class="token punctuation">.</span>a<span class="token punctuation">)</span></span>
<span class="line">sonic <span class="token operator">=</span> ultrasonic<span class="token punctuation">(</span>sda<span class="token operator">=</span><span class="token number">20</span><span class="token punctuation">,</span>scl<span class="token operator">=</span><span class="token number">19</span><span class="token punctuation">)</span></span>
<span class="line">oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'等待扫描...'</span><span class="token punctuation">)</span></span>
<span class="line">rf <span class="token operator">=</span> scan_rfid<span class="token punctuation">.</span>scanning<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">sn <span class="token operator">=</span> rf<span class="token punctuation">.</span>serial_number<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">while</span> <span class="token boolean">True</span><span class="token punctuation">:</span></span>
<span class="line">    v <span class="token operator">=</span> <span class="token number">100</span> <span class="token operator">-</span> sonic<span class="token punctuation">.</span>distance<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">    oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'奶牛编号: '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>sn<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\n产奶量: '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>v<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> k<span class="token punctuation">.</span>status<span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token number">1</span><span class="token punctuation">:</span></span>
<span class="line">        mqttclient<span class="token punctuation">.</span>publish<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">'5b47fWllPg'</span><span class="token punctuation">,</span> content<span class="token operator">=</span><span class="token string">'奶牛编号: '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>sn<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\\n产奶量: '</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>v<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./py/u5l24_学习活动3.py" download>点击下载-u5l24_学习活动3.py</a></p>
</div></template>


