<template><div><h1 id="信息科技八年级-第五单元-第21课-文物保护新手段" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第五单元-第21课-文物保护新手段"><span>信息科技八年级-第五单元-第21课-文物保护新手段</span></a></h1>
<p>PYTHON代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> mqttclient<span class="token punctuation">,</span> pin<span class="token punctuation">,</span> speaker<span class="token punctuation">,</span> dht<span class="token punctuation">,</span> oled<span class="token punctuation">,</span> wifi</span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span> timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span> client_id<span class="token operator">=</span><span class="token string">'a73ac31a4c'</span><span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'a73acPABoi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'a73ackRR4c'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> time</span>
<span class="line">p1 <span class="token operator">=</span> pin<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span></span>
<span class="line">p2 <span class="token operator">=</span> pin<span class="token punctuation">(</span><span class="token number">15</span><span class="token punctuation">)</span></span>
<span class="line">s1 <span class="token operator">=</span> speaker<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">t <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line">h <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line"><span class="token keyword">while</span> <span class="token boolean">True</span><span class="token punctuation">:</span></span>
<span class="line">    temp <span class="token operator">=</span> dht<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span>read<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">0</span><span class="token punctuation">]</span></span>
<span class="line">    hum <span class="token operator">=</span> dht<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span>read<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span></span>
<span class="line">    oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">'温度：'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>temp<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\n湿度：'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>hum<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    mqttclient<span class="token punctuation">.</span>publish<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">'a73acaCSvY'</span><span class="token punctuation">,</span> content<span class="token operator">=</span><span class="token string">'温度：'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>temp<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'\\n湿度：'</span> <span class="token operator">+</span> <span class="token builtin">str</span><span class="token punctuation">(</span>hum<span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> temp <span class="token operator">></span> <span class="token number">28</span> <span class="token keyword">or</span> temp <span class="token operator">&lt;</span> <span class="token number">26</span><span class="token punctuation">:</span></span>
<span class="line">        p1<span class="token punctuation">.</span>write_digital<span class="token punctuation">(</span>value<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">        t <span class="token operator">=</span> t <span class="token operator">+</span> <span class="token number">1</span></span>
<span class="line">    <span class="token keyword">else</span><span class="token punctuation">:</span></span>
<span class="line">        p1<span class="token punctuation">.</span>write_digital<span class="token punctuation">(</span>value<span class="token operator">=</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">        t <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line">    <span class="token keyword">if</span> hum <span class="token operator">></span> <span class="token number">70</span> <span class="token keyword">or</span> hum <span class="token operator">&lt;</span> <span class="token number">60</span><span class="token punctuation">:</span></span>
<span class="line">        p2<span class="token punctuation">.</span>write_digital<span class="token punctuation">(</span>value<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">        h <span class="token operator">=</span> h <span class="token operator">+</span> <span class="token number">1</span></span>
<span class="line">    <span class="token keyword">else</span><span class="token punctuation">:</span></span>
<span class="line">        p2<span class="token punctuation">.</span>write_digital<span class="token punctuation">(</span>value<span class="token operator">=</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">        h <span class="token operator">=</span> <span class="token number">0</span></span>
<span class="line">    <span class="token keyword">if</span> t <span class="token operator">>=</span> <span class="token number">30</span> <span class="token keyword">or</span> h <span class="token operator">>=</span> <span class="token number">30</span><span class="token punctuation">:</span></span>
<span class="line">        s1<span class="token punctuation">.</span>tone<span class="token punctuation">(</span>freq<span class="token operator">=</span><span class="token number">1000</span><span class="token punctuation">,</span> dur<span class="token operator">=</span><span class="token number">1000</span><span class="token punctuation">)</span></span>
<span class="line">    time<span class="token punctuation">.</span>sleep<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./py/u5l21_学习活动3.py" download>点击下载-u5l21_学习活动3.py</a></p>
</div></template>


