<template><div><h1 id="信息科技八年级-第六单元-第30课-系统安全需升级" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第六单元-第30课-系统安全需升级"><span>信息科技八年级-第六单元-第30课-系统安全需升级</span></a></h1>
<p>PYTHON代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> servo<span class="token punctuation">,</span> wifi<span class="token punctuation">,</span> mqttclient</span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span> timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span> client_id<span class="token operator">=</span><span class="token string">'5b47f573ff'</span><span class="token punctuation">,</span> user<span class="token operator">=</span><span class="token string">'5b47fviXMJ'</span><span class="token punctuation">,</span> psd<span class="token operator">=</span><span class="token string">'5b47fNb18u'</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> time</span>
<span class="line"></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">open</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    <span class="token keyword">global</span> msg<span class="token punctuation">,</span> servo<span class="token punctuation">,</span> status<span class="token punctuation">,</span> s<span class="token punctuation">,</span> blink<span class="token punctuation">,</span> mouth</span>
<span class="line">    servo<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">100</span><span class="token punctuation">)</span></span>
<span class="line">    time<span class="token punctuation">.</span>sleep<span class="token punctuation">(</span><span class="token number">1.5</span><span class="token punctuation">)</span></span>
<span class="line">    servo<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line"><span class="token keyword">import</span> ujson</span>
<span class="line"></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">receive_3a2ddfHhTw</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    <span class="token keyword">global</span> mouth<span class="token punctuation">,</span> blink<span class="token punctuation">,</span> s<span class="token punctuation">,</span> status<span class="token punctuation">,</span> servo<span class="token punctuation">,</span> msg</span>
<span class="line">    msg <span class="token operator">=</span> mqttclient<span class="token punctuation">.</span>message<span class="token punctuation">(</span><span class="token string">"3a2ddfHhTw"</span><span class="token punctuation">)</span></span>
<span class="line">    status <span class="token operator">=</span> ujson<span class="token punctuation">.</span>loads<span class="token punctuation">(</span>msg<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'status'</span><span class="token punctuation">]</span></span>
<span class="line">    blink <span class="token operator">=</span> ujson<span class="token punctuation">.</span>loads<span class="token punctuation">(</span>msg<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'blink'</span><span class="token punctuation">]</span></span>
<span class="line">    mouth <span class="token operator">=</span> ujson<span class="token punctuation">.</span>loads<span class="token punctuation">(</span>msg<span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token string">'mouth_open'</span><span class="token punctuation">]</span></span>
<span class="line">    <span class="token keyword">if</span> status <span class="token operator">==</span> <span class="token number">1</span> <span class="token keyword">and</span> blink <span class="token operator">></span> <span class="token number">1</span> <span class="token keyword">and</span> mouth <span class="token operator">></span> <span class="token number">1</span><span class="token punctuation">:</span></span>
<span class="line">        <span class="token builtin">open</span><span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">mqttclient<span class="token punctuation">.</span>received<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">"3a2ddfHhTw"</span><span class="token punctuation">,</span> callback<span class="token operator">=</span>receive_3a2ddfHhTw<span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./py/u6l30_学习活动1.py" download>点击下载-u6l30_学习活动1.py</a></p>
</div></template>


