<template><div><h1 id="信息科技八年级-第一单元-第4课-物物相连有价值" tabindex="-1"><a class="header-anchor" href="#信息科技八年级-第一单元-第4课-物物相连有价值"><span>信息科技八年级-第一单元-第4课-物物相连有价值</span></a></h1>
<img src="@source/educore/img/u1_l4_1.png" alt="u1_l4_1" style="width:700px;">
<p>生成代码:</p>
<div class="language-python line-numbers-mode" data-highlighter="prismjs" data-ext="py"><pre v-pre><code class="language-python"><span class="line"><span class="token keyword">from</span> educore <span class="token keyword">import</span> SoilHumiditySensor<span class="token punctuation">,</span>mqttclient<span class="token punctuation">,</span>oled<span class="token punctuation">,</span>servo<span class="token punctuation">,</span>wifi</span>
<span class="line"><span class="token keyword">import</span> ntptime</span>
<span class="line"><span class="token keyword">import</span> time</span>
<span class="line"></span>
<span class="line"><span class="token keyword">def</span> <span class="token function">receive_a73acJGlOL</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span></span>
<span class="line">    <span class="token keyword">if</span> mqttclient<span class="token punctuation">.</span>message<span class="token punctuation">(</span><span class="token string">'a73acJGlOL'</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token string">'开窗'</span><span class="token punctuation">:</span></span>
<span class="line">        servo<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">90</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">elif</span> mqttclient<span class="token punctuation">.</span>message<span class="token punctuation">(</span><span class="token string">'a73acJGlOL'</span><span class="token punctuation">)</span> <span class="token operator">==</span> <span class="token string">'关窗'</span><span class="token punctuation">:</span></span>
<span class="line">        servo<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line"></span>
<span class="line">wifi<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>ssid<span class="token operator">=</span><span class="token string">'mywifi'</span><span class="token punctuation">,</span>psd<span class="token operator">=</span><span class="token string">'123456789'</span><span class="token punctuation">,</span>timeout<span class="token operator">=</span><span class="token number">10000</span><span class="token punctuation">)</span></span>
<span class="line">ntptime<span class="token punctuation">.</span>settime<span class="token punctuation">(</span><span class="token number">8</span><span class="token punctuation">,</span><span class="token string">"time.windows.com"</span><span class="token punctuation">)</span></span>
<span class="line">mqttclient<span class="token punctuation">.</span>connect<span class="token punctuation">(</span>server<span class="token operator">=</span><span class="token string">'iot.mpython.cn'</span><span class="token punctuation">,</span>port<span class="token operator">=</span><span class="token number">1883</span><span class="token punctuation">,</span>client_id<span class="token operator">=</span><span class="token string">'a73ac43a00'</span><span class="token punctuation">,</span>user<span class="token operator">=</span><span class="token string">'a73acey46G'</span><span class="token punctuation">,</span>psd<span class="token operator">=</span><span class="token string">'a73aciJ9nw'</span><span class="token punctuation">)</span></span>
<span class="line">hum <span class="token operator">=</span> SoilHumiditySensor<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span><span class="token punctuation">.</span>read<span class="token punctuation">(</span><span class="token punctuation">)</span></span>
<span class="line">servo<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">90</span><span class="token punctuation">)</span></span>
<span class="line">mqttclient<span class="token punctuation">.</span>received<span class="token punctuation">(</span>topic<span class="token operator">=</span><span class="token string">'a73acJGlOL'</span><span class="token punctuation">,</span>callback<span class="token operator">=</span>receive_a73acJGlOL<span class="token punctuation">)</span></span>
<span class="line"><span class="token keyword">while</span> <span class="token boolean">True</span><span class="token punctuation">:</span></span>
<span class="line">    oled<span class="token punctuation">.</span><span class="token keyword">print</span><span class="token punctuation">(</span><span class="token string">''</span><span class="token punctuation">.</span>join<span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token builtin">str</span><span class="token punctuation">(</span>time<span class="token punctuation">.</span>localtime<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'点'</span><span class="token punctuation">,</span><span class="token builtin">str</span><span class="token punctuation">(</span>time<span class="token punctuation">.</span>localtime<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'分'</span><span class="token punctuation">,</span><span class="token builtin">str</span><span class="token punctuation">(</span>time<span class="token punctuation">.</span>localtime<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">5</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token string">'秒'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> time<span class="token punctuation">.</span>localtime<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">3</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token number">16</span> <span class="token keyword">and</span> time<span class="token punctuation">.</span>localtime<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">[</span><span class="token number">4</span><span class="token punctuation">]</span> <span class="token operator">==</span> <span class="token number">30</span><span class="token punctuation">:</span></span>
<span class="line">        servo<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line">    time<span class="token punctuation">.</span>sleep<span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span></span>
<span class="line">    <span class="token keyword">if</span> hum <span class="token operator">></span> <span class="token number">2000</span><span class="token punctuation">:</span></span>
<span class="line">        servo<span class="token punctuation">(</span><span class="token number">13</span><span class="token punctuation">)</span><span class="token punctuation">.</span>angle<span class="token punctuation">(</span><span class="token number">0</span><span class="token punctuation">)</span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><a href="./mix/u1l4_学习活动2.mix" download>点击下载-u1l4_学习活动2.mix</a></p>
</div></template>


